"""Unit tests for the Customer model.

Covers:
- Valid creation (CPF and CNPJ).
- Duplicate email / document rejection.
- Invalid document rejection + structlog warning.
- Document sanitisation (punctuation stripped).
- Soft delete (inherited from SoftDeleteModel).
- ``is_active`` default and ``__str__`` masking.
"""

from __future__ import annotations

import uuid

import pytest
from django.core.exceptions import ValidationError
from django.db import IntegrityError

from modules.customers.models import Customer, DocumentType

pytestmark = pytest.mark.unit

# ---------------------------------------------------------------------------
# Well-known valid documents (generated via validate-docbr)
# ---------------------------------------------------------------------------
VALID_CPF = "59860184275"  # 11 digits, valid checksum (generated by validate-docbr)
VALID_CPF_FORMATTED = "598.601.842-75"
VALID_CNPJ = "11222333000181"  # 14 digits, valid checksum
VALID_CNPJ_FORMATTED = "11.222.333/0001-81"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_customer(**overrides) -> Customer:
    """Build and full_clean a Customer, returning the unsaved instance."""
    defaults = {
        "name": "João Silva",
        "document": VALID_CPF,
        "document_type": DocumentType.CPF,
        "email": f"{uuid.uuid4().hex[:8]}@example.com",
    }
    defaults.update(overrides)
    customer = Customer(**defaults)
    customer.full_clean()
    return customer


# ---------------------------------------------------------------------------
# Creation
# ---------------------------------------------------------------------------


class TestCustomerCreation:
    """Happy-path creation with CPF and CNPJ."""

    def test_create_customer_with_valid_cpf(self):
        c = Customer.objects.create(
            name="Maria",
            document=VALID_CPF,
            document_type=DocumentType.CPF,
            email="maria@example.com",
        )
        c.refresh_from_db()
        assert c.name == "Maria"
        assert c.document == VALID_CPF
        assert c.document_type == DocumentType.CPF
        assert c.is_active is True
        assert c.is_deleted is False

    def test_create_customer_with_valid_cnpj(self):
        c = Customer.objects.create(
            name="Empresa XYZ",
            document=VALID_CNPJ,
            document_type=DocumentType.CNPJ,
            email="contato@xyz.com",
        )
        c.refresh_from_db()
        assert c.document == VALID_CNPJ
        assert c.document_type == DocumentType.CNPJ

    def test_id_is_uuid7(self):
        c = Customer.objects.create(
            name="UUID Check",
            document=VALID_CPF,
            document_type=DocumentType.CPF,
            email="uuid@example.com",
        )
        assert isinstance(c.id, uuid.UUID)
        assert c.id.version == 7

    def test_timestamps_set_on_create(self):
        c = Customer.objects.create(
            name="Timestamps",
            document=VALID_CPF,
            document_type=DocumentType.CPF,
            email="ts@example.com",
        )
        assert c.created_at is not None
        assert c.updated_at is not None


# ---------------------------------------------------------------------------
# Sanitisation
# ---------------------------------------------------------------------------


class TestDocumentSanitisation:
    """Document punctuation must be stripped before persistence."""

    def test_cpf_formatted_is_sanitised_on_save(self):
        c = Customer.objects.create(
            name="Sanitise CPF",
            document=VALID_CPF_FORMATTED,
            document_type=DocumentType.CPF,
            email="sanitise-cpf@example.com",
        )
        c.refresh_from_db()
        assert c.document == VALID_CPF  # digits only

    def test_cnpj_formatted_is_sanitised_on_save(self):
        c = Customer.objects.create(
            name="Sanitise CNPJ",
            document=VALID_CNPJ_FORMATTED,
            document_type=DocumentType.CNPJ,
            email="sanitise-cnpj@example.com",
        )
        c.refresh_from_db()
        assert c.document == VALID_CNPJ  # digits only

    def test_sanitisation_via_full_clean(self):
        c = _make_customer(document=VALID_CPF_FORMATTED)
        assert c.document == VALID_CPF


# ---------------------------------------------------------------------------
# Validation — Invalid documents
# ---------------------------------------------------------------------------


class TestDocumentValidation:
    """Invalid CPF/CNPJ must raise ``ValidationError``."""

    def test_invalid_cpf_raises(self):
        with pytest.raises(ValidationError, match="Invalid CPF"):
            _make_customer(document="00000000000", document_type=DocumentType.CPF)

    def test_invalid_cnpj_raises(self):
        with pytest.raises(ValidationError, match="Invalid CNPJ"):
            _make_customer(document="12345678901234", document_type=DocumentType.CNPJ)

    def test_invalid_document_type_raises(self):
        with pytest.raises(ValidationError, match="Invalid document type"):
            _make_customer(document=VALID_CPF, document_type="RG")

    def test_invalid_document_logs_warning(self, caplog):
        """structlog should emit a warning with masked suffix."""
        import logging

        with caplog.at_level(logging.WARNING, logger="modules.customers.models"):
            with pytest.raises(ValidationError):
                _make_customer(document="12345678901", document_type=DocumentType.CPF)
        assert len(caplog.records) >= 1
        record = caplog.records[0]
        assert record.levelno == logging.WARNING
        # The full invalid document must NOT appear in the log message
        assert "12345678901" not in record.getMessage()


# ---------------------------------------------------------------------------
# Uniqueness
# ---------------------------------------------------------------------------


class TestUniquenessConstraints:
    """RN-CLI-001 / RN-CLI-002: document and email must be unique."""

    def test_duplicate_document_raises(self):
        Customer.objects.create(
            name="First",
            document=VALID_CPF,
            document_type=DocumentType.CPF,
            email="first@example.com",
        )
        with pytest.raises(IntegrityError):
            Customer.objects.create(
                name="Second",
                document=VALID_CPF,
                document_type=DocumentType.CPF,
                email="second@example.com",
            )

    def test_duplicate_email_raises(self):
        Customer.objects.create(
            name="First",
            document=VALID_CPF,
            document_type=DocumentType.CPF,
            email="shared@example.com",
        )
        with pytest.raises(IntegrityError):
            Customer.objects.create(
                name="Second",
                document=VALID_CNPJ,
                document_type=DocumentType.CNPJ,
                email="shared@example.com",
            )


# ---------------------------------------------------------------------------
# Soft Delete
# ---------------------------------------------------------------------------


class TestCustomerSoftDelete:
    """RN-CLI-004: soft delete via inherited SoftDeleteModel."""

    def test_delete_sets_deleted_at(self):
        c = Customer.objects.create(
            name="Delete Me",
            document=VALID_CPF,
            document_type=DocumentType.CPF,
            email="delete-me@example.com",
        )
        c.delete()
        c.refresh_from_db()
        assert c.is_deleted is True
        assert c.deleted_at is not None

    def test_soft_deleted_excluded_from_alive(self):
        c = Customer.objects.create(
            name="Alive Check",
            document=VALID_CPF,
            document_type=DocumentType.CPF,
            email="alive-check@example.com",
        )
        c.delete()
        assert not Customer.objects.alive().filter(pk=c.pk).exists()

    def test_soft_deleted_still_in_objects_all(self):
        c = Customer.objects.create(
            name="All Check",
            document=VALID_CPF,
            document_type=DocumentType.CPF,
            email="all-check@example.com",
        )
        c.delete()
        assert Customer.objects.filter(pk=c.pk).exists()

    def test_restore_after_soft_delete(self):
        c = Customer.objects.create(
            name="Restore Me",
            document=VALID_CPF,
            document_type=DocumentType.CPF,
            email="restore-me@example.com",
        )
        c.delete()
        c.restore()
        c.refresh_from_db()
        assert c.is_deleted is False

    def test_hard_delete_removes_from_db(self):
        c = Customer.objects.create(
            name="Hard Delete",
            document=VALID_CPF,
            document_type=DocumentType.CPF,
            email="hard-delete@example.com",
        )
        pk = c.pk
        c.hard_delete()
        assert not Customer.objects.filter(pk=pk).exists()


# ---------------------------------------------------------------------------
# Display / RN-CLI-005
# ---------------------------------------------------------------------------


class TestCustomerDisplay:
    """``__str__`` must mask the document for log safety (RN-CLI-005)."""

    def test_str_masks_document(self):
        c = _make_customer(
            name="Masked",
            document=VALID_CPF,
            document_type=DocumentType.CPF,
        )
        result = str(c)
        assert "Masked" in result
        assert VALID_CPF not in result  # Full document must NOT appear
        assert "***4275" in result  # Only last 4 digits

    def test_str_masks_cnpj(self):
        c = _make_customer(
            name="Corp",
            document=VALID_CNPJ,
            document_type=DocumentType.CNPJ,
            email="corp@example.com",
        )
        result = str(c)
        assert VALID_CNPJ not in result
        assert "***0181" in result


# ---------------------------------------------------------------------------
# is_active default
# ---------------------------------------------------------------------------


class TestIsActiveDefault:
    """Customers are active by default."""

    def test_default_is_active(self):
        c = Customer.objects.create(
            name="Active",
            document=VALID_CPF,
            document_type=DocumentType.CPF,
            email="active@example.com",
        )
        assert c.is_active is True

    def test_can_deactivate(self):
        c = Customer.objects.create(
            name="Deactivate",
            document=VALID_CPF,
            document_type=DocumentType.CPF,
            email="deactivate@example.com",
        )
        c.is_active = False
        c.save(update_fields=["is_active"])
        c.refresh_from_db()
        assert c.is_active is False
