# Generated by Django 5.0.14 on 2026-02-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "name"], name="products_status_name_idx"
            ),
        ),
    ]
