# Generated by Django 5.0.14 on 2026-02-11 22:30

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "Pendente"),
                            ("CONFIRMED", "Confirmado"),
                            ("SEPARATED", "Separado"),
                            ("SHIPPED", "Enviado"),
                            ("DELIVERED", "Entregue"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("CONFIRMED", "Confirmado"),
                            ("SEPARATED", "Separado"),
                            ("SHIPPED", "Enviado"),
                            ("DELIVERED", "Entregue"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "order_status_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "-created_at"], name="osh_order_created_idx"
                    )
                ],
            },
        ),
    ]
