# Generated by Django 5.0.14 on 2026-02-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_add_composite_indexes"),
        ("orders", "0003_order_status_history"),
        ("products", "0002_add_composite_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "-created_at"], name="orders_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "-created_at"], name="orders_customer_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["order", "product"], name="oi_order_product_idx"
            ),
        ),
    ]
