# Generated by Django 5.0.14 on 2026-02-11 22:41

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                ("aggregate_id", models.CharField(max_length=255)),
                ("topic", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PUBLISHED", "Published"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default=None, null=True),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "outbox_events",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["event_type"], name="outbox_event_type_idx"),
                    models.Index(
                        fields=["aggregate_id"], name="outbox_aggregate_id_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="outbox_status_created_idx",
                    ),
                ],
            },
        ),
    ]
