# Generated by Django 5.0.14 on 2026-02-11 21:26

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, default=None, null=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("document", models.CharField(max_length=14, unique=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[("CPF", "CPF"), ("CNPJ", "CNPJ")], max_length=4
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("address", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "customers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="customers_created_idx"),
                    models.Index(fields=["is_active"], name="customers_active_idx"),
                ],
            },
        ),
    ]
