# Generated by Django 5.0.14 on 2026-02-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customer",
            name="customers_active_idx",
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["is_active", "-created_at"], name="customers_active_created_idx"
            ),
        ),
    ]
